#!/bin/sh

divert_gfx () {
	dpkg-divert --add --rename --package kanotix-graphics-common \
		--divert $1.kanotix $1
}

undivert_gfx () {
	dpkg-divert --remove --rename --package kanotix-graphics-common \
		--divert $1.kanotix $1
}

undivert_oldgfx () {
	dpkg-divert --remove $1
}

case "$1" in
	install|upgrade)
		# avoid diversion conflict with previous package which had a broken dpkg-divert implementation
		if dpkg-divert --list kanotix-graphics | grep -q '/usr/share/apps/kicker/pics/kside.png'; then
			dpkg-divert --remove --package kanotix-graphics /usr/share/apps/kicker/pics/kside.png
		fi
		if dpkg --compare-versions "$2" eq "0.6.1"; then
			undivert_oldgfx /usr/share/apps/kicker/pics/kside.png
			undivert_oldgfx /usr/share/icons/crystalsvg/128x128/apps/kmenu.png
			undivert_oldgfx /usr/share/icons/crystalsvg/16x16/apps/kmenu.png
			undivert_oldgfx /usr/share/icons/crystalsvg/22x22/apps/kmenu.png
			undivert_oldgfx /usr/share/icons/crystalsvg/32x32/apps/kmenu.png
			undivert_oldgfx /usr/share/icons/crystalsvg/48x48/apps/kmenu.png
			undivert_oldgfx /usr/share/icons/crystalsvg/64x64/apps/kmenu.png
		fi
		divert_gfx /usr/share/apps/kicker/pics/kside.png
		divert_gfx /usr/share/icons/crystalsvg/128x128/apps/kmenu.png
		divert_gfx /usr/share/icons/crystalsvg/16x16/apps/kmenu.png
		divert_gfx /usr/share/icons/crystalsvg/22x22/apps/kmenu.png
		divert_gfx /usr/share/icons/crystalsvg/32x32/apps/kmenu.png
		divert_gfx /usr/share/icons/crystalsvg/48x48/apps/kmenu.png
		divert_gfx /usr/share/icons/crystalsvg/64x64/apps/kmenu.png
		;;

	abort-upgrade)
		undivert_gfx /usr/share/apps/kicker/pics/kside.png
		undivert_gfx /usr/share/icons/crystalsvg/128x128/apps/kmenu.png
		undivert_gfx /usr/share/icons/crystalsvg/16x16/apps/kmenu.png
		undivert_gfx /usr/share/icons/crystalsvg/22x22/apps/kmenu.png
		undivert_gfx /usr/share/icons/crystalsvg/32x32/apps/kmenu.png
		undivert_gfx /usr/share/icons/crystalsvg/48x48/apps/kmenu.png
		undivert_gfx /usr/share/icons/crystalsvg/64x64/apps/kmenu.png
		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

#DEBHELPER#

exit 0
